services:
    db:
        image: mysql:8.0
        container_name: mysql-db
        restart: always
        environment:
            MYSQL_DATABASE: demodb
            MYSQL_USER: usuario
            MYSQL_PASSWORD: dios1234
            MYSQL_ROOT_PASSWORD: root.1234
        ports:
            - "3303:3306"
        volumes:
            - "mysql_data:/var/liv/mysql"
    app:
        build:
            context: redsmartphone
            dockerfile: Dockerfile
        container_name: rest-app
        restart: always
        depends_on:
            - db
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/demodb
            SPRING_DATASOURCE_USERNAME: usuario
            SPRING_DATASOURCE_PASSWORD: dios1234
            SPRING_JPA_HIBERNATE_DDL_AUTO: update
            SPRING_JPA_SHOW_SQL: "true"
        ports:
            - "9191:8080"
volumes:
    mysql_data:
