services:
    app:
        build:
            context: gameweb
            dockerfile: Dockerfile
        container_name: spring_web_app
        restart: always
        ports:
            - "9090:8080"
